apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  sources:
  - repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: "1.18.0" # Recomendado fixar versao; evite "*"
    helm:
      valueFiles:
      - $values/apps/airflow/values.yaml # Caminho do values.yaml no seu repo Git
  - repoURL: https://github.com/rafael-buttignon/platform-gitops-brw.git # ALTERAR se seu repo/path for outro
    targetRevision: main # ALTERAR para branch/tag desejada (ex: main)
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
